name: Run Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Cache Cypress binary
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/Cypress
          node_modules
        key: cypress-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          cypress-cache-${{ runner.os }}-
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Cypress binary
      run: npx cypress install
    
    - name: Start dev server
      run: npm run dev &
    
    - name: Wait for dev server
      run: npx wait-on http://localhost:5173
      
    - name: Verify app is running
      run: |
        sleep 5
        curl -f http://localhost:5173 || exit 1
    
    - name: Run Cypress tests
      run: npm run test:e2e
